import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <main className='max-w-md mx-auto'>
          {children}
          <nav className="fixed bottom-0 max-w-md flex items-center py-4 justify-evenly w-full border-t">
            <Link href="/">Home</Link>
            <Link href="/program">Program</Link>
            <Link href="/donasi">Donasi</Link>
            <Link href="/akun">Akun</Link>
          </nav>
        </main>
      </body>
    </html>
  )
}
